### ISSUE TITLE
[react] Multiple OpenFeature context changes do not result in multiple re-renders

### ISSUE THREAD

**Issue by Billlynch** [spotify/confidence-openfeature-provider-js#11]
## Expected Behavior
package: integration-react

Given a page with a button to set a new unique global context on the OpenFeaure singleton, each press of the button should result in a rerender of the flags. 

## Current Behavior

Only the first change of context after the initial render has completed will cause an update.

## Steps to Reproduce

see above.

## Your Environment

- NodeJS Version (v18): v18
- Operating System and Version (e.g. Ubuntu 14.04): macOs (M1)
- Browser Information: Chrome 115.0.5790.170

**Comment by andreas-karlsson** [comment]
Closed by #30
